param resourceName string
param serverFarmId string
param location string
param cosmosDbResourceName string
param subscriptioKey string = newGuid()
param applicationInsightResourceName string

resource cosmos 'Microsoft.DocumentDB/databaseAccounts@2025-11-01-preview' existing = {
  name: cosmosDbResourceName
}

resource insights 'Microsoft.Insights/components@2020-02-02' existing = {
  name: applicationInsightResourceName
}

resource web 'Microsoft.Web/sites@2024-11-01' = {
  name: resourceName
  location: location
  kind: 'app,linux,container'
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    siteConfig: {
      appSettings: [
        {
          name: 'COSMOS_DB_CONNECTION_STRING'
          value: cosmos.listConnectionStrings().connectionStrings[0].connectionString
        }
        {
          name: 'MCP_SERVER_KEY'
          value: subscriptioKey
        }
        {
          name: 'RUNNING_IN_PRODUCTION'
          value: 'true'
        }
        {
          name: 'APPLICATIONINSIGHTS_CONNECTION_STRING'
          value: insights.properties.ConnectionString
        }
      ]
      linuxFxVersion: 'sitecontainers'
      acrUseManagedIdentityCreds: true
      alwaysOn: true
    }
    serverFarmId: serverFarmId
    httpsOnly: true
    publicNetworkAccess: 'Enabled'
    autoGeneratedDomainNameLabelScope: 'TenantReuse'
  }
}

output resourceName string = web.name
output principalId string = web.identity.principalId
output mcpServerEndpoint string = web.properties.defaultHostName
output mcpSubscriptionKey string = subscriptioKey
