param resourceName string
param serverFarmId string
param location string

resource web 'Microsoft.Web/sites@2024-11-01' = {
  name: resourceName
  location: location
  kind: 'app,linux,container'
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    siteConfig: {
      appSettings: []
      linuxFxVersion: 'sitecontainers'
      acrUseManagedIdentityCreds: true
      alwaysOn: true
    }
    serverFarmId: serverFarmId
    httpsOnly: true
    publicNetworkAccess: 'Enabled'
    autoGeneratedDomainNameLabelScope: 'TenantReuse'
  }
}

output resourceName string = web.name
output principalId string = web.identity.principalId
