name: Create Azure resources

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - "infra/**"

jobs:
    create-azure-resources:
        env:
            REGION: "canadaeast"
            #AZURE_CORE_OUTPUT: "none"

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6

            - name: Azure Login
              uses: Azure/login@v3.0.0
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            # Temp fix
            # - name: bicep tmp fix
            #   run: az config set bicep.use_binary_from_path=false

            - name: deploy
              id: createResources
              run: |
                  az deployment sub create \
                    --location ${{ env.REGION }} \
                    --name ${{ github.run_id }} \
                    --template-file ./infra/main.bicep \
                    --parameters ./infra/main.bicepparam \
                    --query 'properties.outputs' \
                    --output json > outputs.json

                    cat outputs.json

                    echo "CONTAINER_REGISTRY_NAME=$(jq -r '.container_registry_name.value' outputs.json)" >> $GITHUB_OUTPUT
                    echo "MCP_SERVER_NAME=$(jq -r '.mcp_server_name.value' outputs.json)" >> $GITHUB_OUTPUT

            - name: show
              id: show
              run: |
                  echo ${{ steps.createResources.outputs.CONTAINER_REGISTRY_NAME }}
                  echo ${{ steps.createResources.outputs.MCP_SERVER_NAME }}

            - name: Set secrets using gh CLI
              env:
                  GH_TOKEN: ${{ secrets.PA_TOKEN }}
              run: |
                  gh secret set CONTAINER_REGISTRY_NAME --body "${{ steps.createResources.outputs.CONTAINER_REGISTRY_NAME }}"
                  gh secret set MCP_SERVER_NAME --body "${{ steps.createResources.outputs.MCP_SERVER_NAME }}"
