name: Create Azure resources

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - "infra/**"

jobs:
    create-azure-resources:
        env:
            REGION: "canadaeast"

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6

            - name: Azure Login
              uses: Azure/login@v3.0.0
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: deploy
              id: createResources
              run: |
                  az deployment sub create \
                    --location ${{ env.REGION }} \
                    --name ${{ github.run_id }} \
                    --template-file ./infra/main.bicep \
                    --parameters ./infra/main.bicepparam \
                    --query 'properties.outputs' \
                    --output json > outputs.json
                    
                    echo "CONTAINER_REGISTRY_NAME=$(jq -r '.container_registry_name.value' outputs.json)" >> $GITHUB_OUTPUT
                    echo "MCP_SERVER_NAME=$(jq -r '.mcp_server_name.value' outputs.json)" >> $GITHUB_OUTPUT
                    echo "PROJECT_ENDPOINT=$(jq -r '.project_endpoint.value' outputs.json)" >> $GITHUB_OUTPUT
                    echo "CHAT_COMPLETION_MODEL=$(jq -r '.chat_completion_model.value' outputs.json)" >> $GITHUB_OUTPUT
                    echo "COSMOS_DB_RESOURCE_NAME=$(jq -r '.cosmos_db_resource_name.value' outputs.json)" >> $GITHUB_OUTPUT
                    echo "RESOURCE_GROUP_NAME=$(jq -r '.resource_group_name.value' outputs.json)" >> $GITHUB_OUTPUT

            - name: Set secrets using gh CLI
              env:
                  GH_TOKEN: ${{ secrets.PA_TOKEN }}
              run: |
                  gh secret set CONTAINER_REGISTRY_NAME --body "${{ steps.createResources.outputs.CONTAINER_REGISTRY_NAME }}"
                  gh secret set MCP_SERVER_NAME --body "${{ steps.createResources.outputs.MCP_SERVER_NAME }}"
                  gh secret set PROJECT_ENDPOINT --body "${{ steps.createResources.outputs.PROJECT_ENDPOINT }}"
                  gh secret set CHAT_COMPLETION_MODEL --body "${{ steps.createResources.outputs.CHAT_COMPLETION_MODEL }}"
                  gh secret set COSMOS_DB_RESOURCE_NAME --body "${{ steps.createResources.outputs.COSMOS_DB_RESOURCE_NAME }}"
                  gh secret set RESOURCE_GROUP_NAME --body "${{ steps.createResources.outputs.RESOURCE_GROUP_NAME }}"
