name: Deploy MCP Server

on:
    workflow_dispatch:

jobs:
    build-and-deploy-mcp-server:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6

            - name: Azure Login
              uses: Azure/login@v3.0.0
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Build and Push image
              run: |
                  az acr login -n ${{ secrets.CONTAINER_REGISTRY_NAME }}
                  az acr build -r ${{ secrets.CONTAINER_REGISTRY_NAME }} -t wealth-mcp-server:${{ github.sha }} -t wealth-mcp-server:latest --build-arg BUILDKIT_INLINE_CACHE=1 .
              working-directory: src/wealth-data-mcp

            - uses: azure/webapps-deploy@v2
              with:
                  app-name: ${{secrets.MCP_SERVER_NAME}}
                  images: "${{secrets.CONTAINER_REGISTRY_NAME}}.azurecr.io/wealth-mcp-server:${{ github.sha }}"
